### ISSUE TITLE
[FEATURE REQUEST] 请求微信 4.0 的打包服务

### ISSUE THREAD

**Issue by SphenHe** [weearc/obs-home-weearcm-version-checker#1]
微信已经推出微信4.0, 且在[官网](https://linux.weixin.qq.com)上传了 RPM Package. 请问您可以将这个 package 打包并上传到 [repo:weearcm](https://build.opensuse.org/project/show/home:weearcm) 中吗, 非常感谢!

**Comment by weearc** [comment]
感谢您的反馈，最近事情比较多，预计最早周五测试打包。

**Comment by weearc** [comment]
@SphenHe wechat的源包组(空包)已经上传至obs,后期将通过依赖变更来更改包名，wechat linux今晚开始测试打包

**Comment by weearc** [comment]
@SphenHe obs上已出包，可以尝试更新
